services:
    pgsql:
        image: oroinc/pgsql:13.7-1-alpine
        ports:
            - "5432:5432"
        labels:
            com.symfony.server.service-prefix: ORO_DB
        environment:
            POSTGRES_USER: oro_db_user
            POSTGRES_DB: oro_db
            POSTGRES_PASSWORD: oro_db_pass
            POSTGRES_ROOT_PASSWORD: oro_db_pass
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: "pg_isready -U$${POSTGRES_USER} -d$${POSTGRES_DB}"
            interval: 5s
            timeout: 30s
            start_period: 40s
        restart: on-failure
    web:
        image: nginx:latest
        ports:
            - 8083:8080
            - 80:80
            - 443:443
        volumes:
            - ./code:/code
            - ./nginx/conf.d.oro:/etc/nginx/conf.d
            - ./certs:/certs
        links:
            - php8.3
    php8.3:
        hostname: localServer
        build: './php8.3'
        volumes:
            - ./code:/code
            - ./php8.3/php-code/disable_xdebug.sh:/disable_xdebug.sh
            - ./php8.3/php-code/enable_xdebug.sh:/enable_xdebug.sh
        expose:
            - 9000
            - 9003
        working_dir: /code/cbc
        links:
          - redis
          - mailcatcher
          - pgsql
          - elasticsearch8
          - rabbitmq
    mailcatcher:
        image: yappabe/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"
    elasticsearch8:
        image: elasticsearch:8.4.1
        command: bin/elasticsearch -Eingest.geoip.downloader.enabled=false
        environment:
            discovery.type: "single-node"
            cluster.name: docker-cluster
            bootstrap.memory_lock: "true"
            network.host: 0.0.0.0
            path.repo: "/tmp"
            ES_JAVA_OPTS: -Xms2g -Xmx2g
            xpack.security.enabled: "false"
            xpack.security.http.ssl.enabled: "false"
            xpack.security.transport.ssl.enabled: "false"
        ports: ["9200", "9300"]
        volumes:
            - elasticsearch8Volume:/usr/share/elasticsearch/data
        labels:
            com.symfony.server.service-prefix: ORO_SEARCH
        restart: on-failure
    rabbitmq:
        image: oroinc/rabbitmq:3.9-1-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        labels:
            com.symfony.server.service-prefix: ORO_MQ
        environment:
            RABBITMQ_DEFAULT_USER: oro_mq_user
            RABBITMQ_DEFAULT_PASS: oro_mq_pass
        restart: on-failure
    redis:
        image: redis:6.2
        restart: always
        ports:
            - 6379:6379
        environment:
            TZ: Asia/Shanghai
volumes:
    postgres-data: {}
    elasticsearch8Volume: {}
